server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #不需要去检索服务
    #设置于eureka交互的地址查询服务和注册服务地址
    service-url:
      #多台server机器
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #单机版 defaultZone: http://eureka7001.com/eureka/  http://${eureka.instance.hostname}:${server.port}/eureka/